apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-artifacts
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-artifacts
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argo-artifacts
  namespace: argo
roleRef:
  kind: Role
  name: argo-artifacts
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::390402568971:role/AdminForMyKube
  name: argo-artifacts
  namespace: argo