---
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: github
  rules:
  - apiGroups: [""]
    resources: ["workflows.argoproj.io"]
    verbs: ["list","update"]
  - apiGroups: [""]
    resources: ["pods", "pods/portforward"]
    verbs: ["get", "list", "create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github
subjects:
- kind: ServiceAccount
  name: github
  namespace: argo
roleRef:
  kind: Role
  name: github
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: github.service-account-token
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token