apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: push-template
  namespace: argo
spec:
  entrypoint: artifact-example
  templates:
    steps:
    - - name: generate-manifest
        template: json-combiner
    - - name: consume-manifest
        template: openapi-previewer
        arguments:
          artifacts:
          - name: jobmanifest
            from: "{{steps.generate-artifact.outputs.artifacts.jobmanifest}}"
    - name: json-combiner
      arguments:
        parameters:
          - name: jobmanifest
            value: |
              {
                "checkId": "{{workflow.parameters.checkId}}",
                "pr": "{{workflow.parameters.pr}}",
                "repo": "{{workflow.parameters.repo}}",
                "headSha": "{{workflow.parameters.headSha}}",
                "baseRef": "{{workflow.parameters.baseRef}}",
                "ghToken": "{{workflow.parameters.ghToken}}"
              }
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo '{{inputs.parameters.jobmanifest}}' | tee /tmp/jobmanifest.json"]
      outputs:
        artifacts:
        - name: jobmanifest
          path: /tmp/jobmanifest.json
    - name: openapi-previewer
      arguments:
        parameters:
          - name: jobmanifest
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo '{{inputs.parameters.jobmanifest}}' | tee /tmp/jobmanifest.json"]
