---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:390402568971:certificate/e52d37f8-7666-4ba9-8c43-1553cacb5ce0
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    external-dns.alpha.kubernetes.io/hostname: argo.hitchpin.dev
  name: argo
  namespace: argo
spec:
  rules:
    - host: argo.hitchpin.dev
      http:
        paths:
          - backend:
              service:
                name: argo-server
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - argo.hitchpin.dev