apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: push-template
  namespace: argo
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: checkId
            value: "{{workflow.parameters.checkId}}"
      container:
        image: busybox
        command: [echo]
        args: ["{{inputs.parameters.checkId}}"]
  entrypoint: main